//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GCT_PROGRAMACION_MEDICA
    {
        public int idEmpleado { get; set; }
        public int idInmueble { get; set; }
        public string prestaciones { get; set; }
        public string disPrestaciones { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime horaInicio { get; set; }
        public System.DateTime horaFin { get; set; }
        public string anotaciones { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public int idProgramacion { get; set; }
    
        public virtual T_GG_EMPLEADO T_GG_EMPLEADO { get; set; }
        public virtual T_GG_INMUEBLE T_GG_INMUEBLE { get; set; }
    }
}
