//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GDA_PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GDA_PACIENTE()
        {
            this.T_GDA_HISTORIA_CLINICA = new HashSet<T_GDA_HISTORIA_CLINICA>();
            this.T_GUQ_RESERVA_SALA_OPERACIÓN = new HashSet<T_GUQ_RESERVA_SALA_OPERACIÓN>();
            this.T_GUQ_PACIENTE_ESTADO_UCI = new HashSet<T_GUQ_PACIENTE_ESTADO_UCI>();
        }
    
        public int idPaciente { get; set; }
        public string nomPaciente { get; set; }
        public string numDNI { get; set; }
        public string dirPaciente { get; set; }
        public string telPaciente { get; set; }
        public string mailPaciente { get; set; }
        public int edad { get; set; }
        public System.DateTime fecNacimiento { get; set; }
        public string segmentacion { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GDA_HISTORIA_CLINICA> T_GDA_HISTORIA_CLINICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_RESERVA_SALA_OPERACIÓN> T_GUQ_RESERVA_SALA_OPERACIÓN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_PACIENTE_ESTADO_UCI> T_GUQ_PACIENTE_ESTADO_UCI { get; set; }
    }
}
