//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GG_INMUEBLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GG_INMUEBLE()
        {
            this.T_GCT_PROGRAMACION_MEDICA = new HashSet<T_GCT_PROGRAMACION_MEDICA>();
            this.T_GUQ_RESERVA_SALA_OPERACIÓN = new HashSet<T_GUQ_RESERVA_SALA_OPERACIÓN>();
            this.T_GUQ_TIPO_OPERACIÓN = new HashSet<T_GUQ_TIPO_OPERACIÓN>();
        }
    
        public int idInmueble { get; set; }
        public int idArea { get; set; }
        public string dscTipoInmueble { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GCT_PROGRAMACION_MEDICA> T_GCT_PROGRAMACION_MEDICA { get; set; }
        public virtual T_GUQ_AREA T_GUQ_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_RESERVA_SALA_OPERACIÓN> T_GUQ_RESERVA_SALA_OPERACIÓN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_TIPO_OPERACIÓN> T_GUQ_TIPO_OPERACIÓN { get; set; }
    }
}
