//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GUQ_INSUMO()
        {
            this.T_GUQ_INSUMO_TIPOOPERACION = new HashSet<T_GUQ_INSUMO_TIPOOPERACION>();
        }
    
        public int idInsumo { get; set; }
        public string dscInsumo { get; set; }
        public double costoInsumo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_INSUMO_TIPOOPERACION> T_GUQ_INSUMO_TIPOOPERACION { get; set; }
    }
}
