//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_PRESUPUESTO_PARTIDA
    {
        public int idPresupuestoPartida { get; set; }
        public int idPresupuesto { get; set; }
        public int idPartida { get; set; }
        public double montoPartida { get; set; }
    
        public virtual T_GUQ_PARTIDA T_GUQ_PARTIDA { get; set; }
        public virtual T_GUQ_PRESUPUESTO T_GUQ_PRESUPUESTO { get; set; }
    }
}
