//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_PARTIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GUQ_PARTIDA()
        {
            this.T_GUQ_ESTADÍSTICA_RECURSOS = new HashSet<T_GUQ_ESTADÍSTICA_RECURSOS>();
            this.T_GUQ_PRESUPUESTO_PARTIDA = new HashSet<T_GUQ_PRESUPUESTO_PARTIDA>();
        }
    
        public int idPartida { get; set; }
        public string dscPartida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_ESTADÍSTICA_RECURSOS> T_GUQ_ESTADÍSTICA_RECURSOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_PRESUPUESTO_PARTIDA> T_GUQ_PRESUPUESTO_PARTIDA { get; set; }
    }
}
