//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_AREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_GUQ_AREA()
        {
            this.T_GG_EMPLEADO = new HashSet<T_GG_EMPLEADO>();
            this.T_GG_INMUEBLE = new HashSet<T_GG_INMUEBLE>();
            this.T_GUQ_ESTADÍSTICA_RECURSOS = new HashSet<T_GUQ_ESTADÍSTICA_RECURSOS>();
            this.T_GUQ_PRESUPUESTO = new HashSet<T_GUQ_PRESUPUESTO>();
        }
    
        public int idArea { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_EMPLEADO> T_GG_EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GG_INMUEBLE> T_GG_INMUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_ESTADÍSTICA_RECURSOS> T_GUQ_ESTADÍSTICA_RECURSOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_GUQ_PRESUPUESTO> T_GUQ_PRESUPUESTO { get; set; }
    }
}
