//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2.Entidades.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUQ_ESTADÍSTICA_RECURSOS
    {
        public int idEstadisticaRecurso { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
        public int idArea { get; set; }
        public double montoHistórico { get; set; }
        public int idPartida { get; set; }
    
        public virtual T_GUQ_AREA T_GUQ_AREA { get; set; }
        public virtual T_GUQ_PARTIDA T_GUQ_PARTIDA { get; set; }
    }
}
